### ISSUE TITLE
OnSubmitText Listener??

### ISSUE THREAD

**Issue by ThrownFran** [UdiOshi85/SearchToolbarExample#1]
Hi UdiOshi85, excellent work. I will use your library if I can find a way to Submit the query from Keyboard enter button, It is possible? Reason is due to slow server responses with querychangedListener. Thank you

**Comment by UdiOshi85** [comment]
Hi ThrownFran,
Thanks very much for your input, I will update my library soon with your request.

Udi

**Comment by UdiOshi85** [comment]
Hi ThrownFran,
I've update the library. you can now use version 1.2.0
compile 'com.github.udioshi85:libSearchToolbar:1.2.0'

I've expanded the interface and now you need to implement also:
void onSearchSubmitted(String query);

Don't forget to STAR the [library ](https://github.com/UdiOshi85/libSearchToolbar)if you like it :)

I've also update the example app to use it.

If you have any other issue please create new one.

Thanks,
Udi

**Comment by ThrownFran** [comment]
Wonderful UdiOshi85!! Fastest response ever! Gonna try it in my project :D

**Comment by UdiOshi85** [comment]
good luck :) this is a new library so if you find issues let me know ans i'll fix them asap
