### ISSUE TITLE
Animation not working

### ISSUE THREAD

**Issue by kopipangku** [UdiOshi85/SearchToolbarExample#2]
Hello, 
I have try your code, but the animation is not working on my project. when I click search button, it just open the search menu without a transition animation. 

What I copy from your code is: 
manifest, 4 java files, 5 layout (including menu_search.xml), style, strings, and gradle dependencies. 
Is i miss something here?

**Comment by UdiOshi85** [comment]
Hi kopipangku ,

Please note that the animation is enabled on API > 21 .
Check my README at the https://github.com/UdiOshi85/libSearchToolbar 
If you still having issues with API > 21 please send me the device info.

Appreciate if you can open the Issue on the library area (https://github.com/UdiOshi85/libSearchToolbar)
Also, If you like the library please STAR it :)

**Comment by kopipangku** [comment]
Hi @UdiOshi85 , 
Yes, my device is use lower API android. I'll try to find another device then. 
By the way, I like your lib. Star is comming... 

Thanks for your support.

**Comment by UdiOshi85** [comment]
Hi @kopipangku ,

You are more than welcome. all info and other cool stuff are in the [library github](https://github.com/UdiOshi85/libSearchToolbar)

Would appreciate if you can STAR there.
Meanwhile, i'm closing this issue, if you are facing other issues please open them in the above url.
And I will fix them ASAP.

Cheers.

**Comment by kopipangku** [comment]
Excellent 
The STAR is yours.. ;) 

Regards,
